# Site settings
title: AncientGuy
email: MarkBruns@MarkBruns.com
description: Seeing beyond time involves realizing that God IS, but that God is not our servant, our superhero, our anthropomorphized equal. In this existence, humans are trapped by their egos in the Time of their existence; thus unable to see beyond Time as long as they remain attached to the pathetic selfish timebound me-ness of their existence. The Creator always WAS, always IS, always WILL BE ... the Kingdom of Heavan is not something that is coming in the future; your death is the only thing that is coming. Everything dies ... there is no such thing as genuine permanence. Luke 17:20; 
github_username:  AncientGuy

# Build settings
markdown: kramdown
