# Site settings
title: AncientGuy
email: MarkBruns@MarkBruns.com
description: The minimalist, prayer-based life for the most essential WHY
github_username:  AncientGuy
twitter_username: MarkBruns

# Build settings
markdown: kramdown
