# Site settings
title: AncientGuy
email: MarkBruns@MarkBruns.com
description: Seeing beyond Time involves realizing that the ORIGIN of all Origins is defined as God ... and that God IS. Everywhere ... but also that God is not some Old Man, not our servant or some superhero, not some anthropomorphized quasi-equal that we'll dinner with. In this Time-bound existence, humans are trapped by their egos, unable to escape the Time of their existence; thus unable to see why they must work harder at loving others as themselves, not simply as some commandment to do without realizing why, but in order to escape their pathetic selfish timebound me-ness of their existence. The Creator always WAS, always IS, always WILL BE ... the Kingdom of Heavan is not something that is coming in the future; your death is the only thing that is coming. Everything dies and everything that remembers any evidence of you will die and return to the precursors of dust ... there is no such thing as genuine permanence. Luke 17:20; 
github_username:  AncientGuy

# Build settings
markdown: kramdown
