# Site settings
title: AncientGuy
email: MarkBruns@MarkBruns.com
description: God is not your servant, friend, your equal. In this existence, humans are trapped by their egos in Time; unable to see beyond Time as long as they are attached the pathetic selfish timebound me-ness of their existence. The Creator was, is, always will be ... the Kingdom of Heavan is not something that is coming. Luke 17:20; 
github_username:  AncientGuy

# Build settings
markdown: kramdown
